name: Run API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      USER_NAME: ${{ secrets.USER_NAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests pytest python-dotenv
      - name: Run tests
        run: pytest Test_api.py
