name: "Tests of validate package"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unittest:
    name: 'Run tests of validate package'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pytest python-dotenv

    - name: Run API tests
      run: pytest scripts/tests/test_api.py -v

    - name: Run Unittest
      run: |
        cd scripts/tests
        if [ -f "test_validate_format.py" ]; then
          python -m unittest test_validate_format.py --verbose
        fi
        if [ -f "test_validate_links.py" ]; then
          python -m unittest test_validate_links.py --verbose
        fi
        # Si aucun fichier unittest, on skip proprement
        if [ ! -f "test_validate_format.py" ] && [ ! -f "test_validate_links.py" ]; then
          echo "✓ No unittest files found - skipping"
        fi