name: Run API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Ces variables viennent directement des secrets GitHub
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      USER_NAME: ${{ secrets.USER_NAME }}
    steps:
      # 1️⃣ Cloner le repo
      - uses: actions/checkout@v3

      # 2️⃣ Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: pip install requests pytest python-dotenv

      # 4️⃣ Lancer les tests
      - name: Run API tests
        run: pytest Test_api.py -v
