name: "Run API Tests"

# Déclencheurs du workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    name: "Run API tests with pytest"
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Exécuter tous les tests du dossier tests
      - name: Run API tests
        run: pytest tests/ -v
